-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."cabin" add column "max_guest_capacity" integer
--  not null default '2';
